# pandas -2

In [8]:
import pandas as pd

## Let's start with dictionary as Container

In [3]:
person = {
    "first" : "priyanshu",
    "last"  : "verma",
    "email" : "priyanshuverma@gmail.com"
}

In [4]:
person

{'first': 'priyanshu', 'last': 'verma', 'email': 'priyanshuverma@gmail.com'}

### But here the list can store only one value for each key
### lets go for list of values for each key

In [4]:
people = {
    "first" : ["priyanshu","anirudh","naresh"],
    "last" : ["verma","kushwah","kumar"],
    "email" : ["priyanshukumarv984@gmail.com","anirudh@gmail.com","naresh@gmail.com"]
}

In [5]:
people

{'first': ['priyanshu', 'anirudh', 'naresh'],
 'last': ['verma', 'kushwah', 'kumar'],
 'email': ['priyanshukumarv984@gmail.com',
  'anirudh@gmail.com',
  'naresh@gmail.com']}

In [6]:
#accessing specific value
people['email']

['priyanshukumarv984@gmail.com', 'anirudh@gmail.com', 'naresh@gmail.com']

#### problem with disctionary is: it has very limited functionalities
### hence lets go to pandas and it's data frame

## DataFrame : 2-D data structure (Rows and column)

In [10]:
df = pd.DataFrame(people)

In [11]:
df

       first     last                         email
0  priyanshu    verma  priyanshukumarv984@gmail.com
1    anirudh  kushwah             anirudh@gmail.com
2     naresh    kumar              naresh@gmail.com

In [12]:
#accessing single value
df["email"]

0    priyanshukumarv984@gmail.com
1               anirudh@gmail.com
2                naresh@gmail.com
Name: email, dtype: object

### the above printed object is a series
## Series : 1-D array (rows of single column)
# DataFrame : is a container of multipleseries

In [13]:
type(df['email'])

pandas.core.series.Series

In [14]:
df.email

0    priyanshukumarv984@gmail.com
1               anirudh@gmail.com
2                naresh@gmail.com
Name: email, dtype: object

In [16]:
# acceessing multiple column
df[["first","last"]]

       first     last
0  priyanshu    verma
1    anirudh  kushwah
2     naresh    kumar

In [17]:
df

       first     last                         email
0  priyanshu    verma  priyanshukumarv984@gmail.com
1    anirudh  kushwah             anirudh@gmail.com
2     naresh    kumar              naresh@gmail.com

In [19]:
# knowing all the column of data frame
df.columns

Index(['first', 'last', 'email'], dtype='object')

## To access rows loc and iloc are used
### loc : it is lable-based
### iloc : it is integer positioned-based

In [20]:
# To acess single row
df.iloc[0]

first                       priyanshu
last                            verma
email    priyanshukumarv984@gmail.com
Name: 0, dtype: object

In [21]:
# To accessing multiple rows
df.iloc[[0,1]]

       first     last                         email
0  priyanshu    verma  priyanshukumarv984@gmail.com
1    anirudh  kushwah             anirudh@gmail.com

In [22]:
#rows of specific column only
df.iloc[[0,1],2]

0    priyanshukumarv984@gmail.com
1               anirudh@gmail.com
Name: email, dtype: object

In [23]:
# multiple rows and multiple column
df.iloc[[0,1],[0,1]]

       first     last
0  priyanshu    verma
1    anirudh  kushwah

In [24]:
df.loc[0]

first                       priyanshu
last                            verma
email    priyanshukumarv984@gmail.com
Name: 0, dtype: object

In [25]:
df.loc[[0,1],["email","first"]]

                          email      first
0  priyanshukumarv984@gmail.com  priyanshu
1             anirudh@gmail.com    anirudh

## Reading from csv file

In [27]:
df = pd.read_csv('sampleData2020/survey_results_public.csv')
schema_df = pd.read_csv('sampleData2020/survey_results_schema.csv')

In [28]:
pd.set_option('display.max_columns',61)
pd.set_option('display.max_rows',61)

In [30]:
df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

In [31]:
schema_df

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order ...
1,MainBranch,Which of the following options best describes ...
2,Hobbyist,Do you code as a hobby?
3,Age,What is your age (in years)? If you prefer not...
4,Age1stCode,At what age did you write your first line of c...
5,CompFreq,"Is that compensation weekly, monthly, or yearly?"
6,CompTotal,What is your current total compensation (salar...
7,ConvertedComp,Salary converted to annual USD salaries using ...
8,Country,Where do you live?
9,CurrencyDesc,Which currency do you use day-to-day? If your ...
10,CurrencySymbol,Which currency do you use day-to-day? If your ...
11,DatabaseDesireNextYear,Which database environments have you done exte...
12,DatabaseWorkedWith,Which database environments have you done exte...
13,DevType,Which of the following describe you? Please se...
14,EdLevel,Which of the following best describes the high...
15,Employment,Which of the following best describes your cur...
16,Ethnicity,"Which of the following describe you, if any? P..."
17,Gender,"Which of the following describe you, if any? P..."
18,JobFactors,Imagine that you are deciding between two job ...
19,JobSat,How satisfied are you with your current job? (...
20,JobSeek,Which of the following best describes your cur...
21,LanguageDesireNextYear,"Which programming, scripting, and markup langu..."
22,LanguageWorkedWith,"Which programming, scripting, and markup langu..."
23,MiscTechDesireNextYear,"Which other frameworks, libraries, and tools h..."
24,MiscTechWorkedWith,"Which other frameworks, libraries, and tools h..."
25,NEWCollabToolsDesireNextYear,Which collaboration tools have you done extens...
26,NEWCollabToolsWorkedWith,Which collaboration tools have you done extens...
27,NEWDevOps,Does your company have a dedicated DevOps person?
28,NEWDevOpsImpt,How important is the practice of DevOps to sca...
29,NEWEdImpt,"How important is a formal education, such as a..."
30,NEWJobHunt,"In general, what drives you to look for a new ..."
31,NEWJobHuntResearch,"When job searching, how do you learn more abou..."
32,NEWLearn,How frequently do you learn a new language or ...
33,NEWOffTopic,Do you think Stack Overflow should relax restr...
34,NEWOnboardGood,Do you think your company has a good onboardin...
35,NEWOtherComms,Are you a member of any other online developer...
36,NEWOvertime,How often do you work overtime or beyond the f...
37,NEWPurchaseResearch,"When buying a new tool or software, how do you..."
38,NEWPurpleLink,You search for a coding solution online and th...
39,NEWSOSites,Which of the following Stack Overflow sites ha...
40,NEWStuck,What do you do when you get stuck on a problem...
41,OpSys,What is the primary operating system in which ...
42,OrgSize,Approximately how many people are employed by ...
43,PlatformDesireNextYear,Which platforms have you done extensive develo...
44,PlatformWorkedWith,Which platforms have you done extensive develo...
45,PurchaseWhat,"What level of influence do you, personally, ha..."
46,Sexuality,"Which of the following describe you, if any? P..."
47,SOAccount,Do you have a Stack Overflow account?
48,SOComm,Do you consider yourself a member of the Stack...
49,SOPartFreq,How frequently would you say you participate i...
50,SOVisitFreq,How frequently would you say you visit Stack O...
51,SurveyEase,How easy or difficult was this survey to compl...
52,SurveyLength,How do you feel about the length of the survey...
53,Trans,Are you transgender?
54,UndergradMajor,What was your primary field of study?
55,WebframeDesireNextYear,Which web frameworks have you done extensive d...
56,WebframeWorkedWith,Which web frameworks have you done extensive d...
57,WelcomeChange,"Compared to last year, how welcome do you feel..."
58,WorkWeekHrs,"On average, how many hours per week do you wor..."
59,YearsCode,"Including any education, how many years have y..."
60,YearsCodePro,"NOT including education, how many years have y..."

In [32]:
#size of dataframe df
df.shape

(64461, 61)

In [33]:
#total column in dataframe
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'CompFreq',
       'CompTotal', 'ConvertedComp', 'Country', 'CurrencyDesc',
       'CurrencySymbol', 'DatabaseDesireNextYear', 'DatabaseWorkedWith',
       'DevType', 'EdLevel', 'Employment', 'Ethnicity', 'Gender', 'JobFactors',
       'JobSat', 'JobSeek', 'LanguageDesireNextYear', 'LanguageWorkedWith',
       'MiscTechDesireNextYear', 'MiscTechWorkedWith',
       'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps',
       'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch',
       'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms',
       'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites',
       'NEWStuck', 'OpSys', 'OrgSize', 'PlatformDesireNextYear',
       'PlatformWorkedWith', 'PurchaseWhat', 'Sexuality', 'SOAccount',
       'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength',
       'Trans', 'UndergradMajor', 'WebframeDesireNextYear',
       'WebframeWorkedWith', 'WelcomeChange', 'WorkWeekHrs', 'YearsCode',
       'YearsCodePro'],
      dtype='object')

In [35]:
# get the row of column hobbyst
df['Hobbyist']

0        Yes
1         No
2        Yes
3        Yes
4        Yes
        ...
64456    Yes
64457    Yes
64458    Yes
64459    Yes
64460    Yes
Name: Hobbyist, Length: 64461, dtype: object

### How many values in this Hobbyist column are yes,no

In [36]:
df['Hobbyist'].value_counts()

Hobbyist
Yes    50388
No     14028
Name: count, dtype: int64

In [39]:
df['Age'].value_counts()

Age
25.0    2693
28.0    2412
30.0    2406
26.0    2391
27.0    2338
        ...
34.5       1
14.7       1
97.0       1
3.0        1
14.5       1
Name: count, Length: 110, dtype: int64

In [40]:
df['Gender'].value_counts()

Gender
Man                                                            46013
Woman                                                           3844
Non-binary, genderqueer, or gender non-conforming                385
Man;Non-binary, genderqueer, or gender non-conforming            121
Woman;Non-binary, genderqueer, or gender non-conforming           92
Woman;Man                                                         76
Woman;Man;Non-binary, genderqueer, or gender non-conforming       26
Name: count, dtype: int64

In [41]:
# Access first row of dataframe
df.iloc[0]

Respondent                                                                      1
MainBranch                                         I am a developer by profession
Hobbyist                                                                      Yes
Age                                                                           NaN
Age1stCode                                                                     13
CompFreq                                                                  Monthly
CompTotal                                                                     NaN
ConvertedComp                                                                 NaN
Country                                                                   Germany
CurrencyDesc                                                        European Euro
CurrencySymbol                                                                EUR
DatabaseDesireNextYear                                       Microsoft SQL Server
DatabaseWorkedWith                      Elasticsearch;Microsoft SQL Server;Oracle
DevType                         Developer, desktop or enterprise applications;...
EdLevel                           Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
Employment                      Independent contractor, freelancer, or self-em...
Ethnicity                                            White or of European descent
Gender                                                                        Man
JobFactors                      Languages, frameworks, and other technologies ...
JobSat                                                         Slightly satisfied
JobSeek                              I am not interested in new job opportunities
LanguageDesireNextYear                                     C#;HTML/CSS;JavaScript
LanguageWorkedWith                                         C#;HTML/CSS;JavaScript
MiscTechDesireNextYear                                          .NET Core;Xamarin
MiscTechWorkedWith                                                 .NET;.NET Core
NEWCollabToolsDesireNextYear               Microsoft Teams;Microsoft Azure;Trello
NEWCollabToolsWorkedWith             Confluence;Jira;Slack;Microsoft Azure;Trello
NEWDevOps                                                                      No
NEWDevOpsImpt                                                  Somewhat important
NEWEdImpt                                                        Fairly important
NEWJobHunt                                                                    NaN
NEWJobHuntResearch                                                            NaN
NEWLearn                                                              Once a year
NEWOffTopic                                                              Not sure
NEWOnboardGood                                                                NaN
NEWOtherComms                                                                  No
NEWOvertime                                      Often: 1-2 days per week or more
NEWPurchaseResearch             Start a free trial;Ask developers I know/work ...
NEWPurpleLink                                                              Amused
NEWSOSites                       Stack Overflow (public Q&A for anyone who codes)
NEWStuck                        Visit Stack Overflow;Go for a walk or other ph...
OpSys                                                                     Windows
OrgSize                                                          2 to 9 employees
PlatformDesireNextYear             Android;iOS;Kubernetes;Microsoft Azure;Windows
PlatformWorkedWith                                                        Windows
PurchaseWhat                                                                  NaN
Sexuality                                                 Straight / Heterosexual
SOAccount                                                                      No
SOComm                                                             No, not at all
SOPartFreq                                                                    NaN
SOVisitFreq                                                Multiple times per day
SurveyEase                                             Neither easy nor difficult
SurveyLength                                                Appropriate in length
Trans                                                                          No
UndergradMajor                  Computer science, computer engineering, or sof...
WebframeDesireNextYear                                               ASP.NET Core
WebframeWorkedWith                                           ASP.NET;ASP.NET Core
WelcomeChange                             Just as welcome now as I felt last year
WorkWeekHrs                                                                  50.0
YearsCode                                                                      36
YearsCodePro                                                                   27
Name: 0, dtype: object

In [43]:
# Access top 3 rows of "Hobbyist" column
df.loc[[0,1,2],'Hobbyist']

0    Yes
1     No
2    Yes
Name: Hobbyist, dtype: object